export const signInText = {
    RU: {
        header: 'Вход',
        email: 'Электронная почта',
        password: 'Пароль',
        signIn: 'Войти',
        forgotPassword: 'Забыли пароль?',
        signUp: 'Зарегистрироваться',
        teacher: 'Учитель',
        student: 'Студент',
    },
    KZ: {
        header: 'Кіру',
        email: 'Электрондық пошта',
        password: 'Пароль',
        signIn: 'Кіру',
        forgotPassword: 'Парольді қалдырып көр?',
        signUp: 'Тіркелу',
        teacher: 'Учитель',
        student: 'Студент',
    },
    EN: {
        header: 'Sign in',
        email: 'Email',
        password: 'Password',
        signIn: 'Sign in',
        forgotPassword: 'Forgot password?',
        signUp: 'Sign up',
        teacher: 'Teacher',
        student: 'Student',
    },
}