export const signUpText = {
    RU: {
        header: 'Регистрация',
        email: 'Электронная почта',
        password: 'Пароль',
        firstName: 'Имя',
        lastName: 'Фамилия',
        signIn: 'Регистрация',
        dateOfBirth: 'Дата рождения',
        workExperience: 'Опыт работы (лет)',
        currentWork: 'Текущая работа',
        signUp: 'Зарегистрироваться',
    },
    KZ: {
        header: 'Тіркелу',
        email: 'Электрондық пошта',
        password: 'Пароль',
        firstName: 'Аты',
        lastName: 'Тегі',
        signIn: 'Тіркелу',
        dateOfBirth: 'Туған күні',
        workExperience: 'Жұмыс қызметі(жыл)',
        currentWork: 'Қазіргі жұмыс орны',
        signUp: 'Тіркелу',
    },
    EN: {
        header: 'Sign up',
        email: 'Email',
        password: 'Password',
        firstName: 'First name',
        lastName: 'Last name',
        signIn: 'Sign in',
        dateOfBirth: 'Date of birth',
        workExperience: 'Work experience(years)',
        currentWork: 'Current work',
        signUp: 'Sign up',
    },
}