export const lessonsPageText = {
    RU: {
        header: 'Уроки',
        createLesson: {
            lang: 'Выберите язык',
            title: 'Создать урок',
            lesson: 'Урок',
            subject: 'Предмет',
            lessonTitle: 'Тема урока',
            lessonDescription: 'Описание урока',
            createLesson: 'Создать урок',
        },
        lessonPage: {
            author: 'Автор',
            date: 'Дата',
            subject: 'Предмет',
            edit: 'Редактировать',
            save: 'Сохранить',
            lang: 'Язык',
            link: 'Ссылка',
            description: 'Описание',
            lesson: 'Урок',
            assesment: 'Оценка',
            comments: 'Комментарии',
        }
    },
    KZ: {
        header: 'Сабақтар',
        createLesson: {
            lang: 'Тілді таңдаңыз',
            title: 'Сабақ құру',
            lesson: 'Сабақ',
            subject: 'Пән',
            lessonTitle: 'Сабақтың тақырыбы',
            lessonDescription: 'Сабақтың сипаттамасы',
            createLesson: 'Растау',
        },
        lessonPage: {
            author: 'Автор',
            date: 'Күні',
            subject: 'Пән',
            edit: 'Редакциялау',
            save: 'Сақтау',
            lang: 'Тілі',
            link: 'Сілтеме',
            description: 'Сипаттамасы',
            lesson: 'Сабақ',
            assesment: 'Бағалау',
            comments: 'Пікірлер',
        }
    },
    EN: {
        header: 'Lessons',
        createLesson: {
            lang: 'Select language',
            title: 'Create lesson',
            lesson: 'Lesson',
            subject: 'Subject',
            lessonTitle: 'Lesson title',
            lessonDescription: 'Lesson description',
            createLesson: 'Publish lesson',
        },
        lessonPage: {
            author: 'Author',
            date: 'Date',
            subject: 'Subject',
            edit: 'Edit',
            save: 'Save',
            lang: 'Language',
            link: 'Link',
            description: 'Description',
            lesson: 'Lesson',
            assesment: 'Assessment',
            comments: 'Comments',
        }
    },
}