export const signUpText = {
    RU: {
        header: 'Регистрация',
        teacher: 'Преподаватель',
        student: 'Студент',
        email: 'Электронная почта',
        password: 'Пароль',
        firstName: 'Имя',
        lastName: 'Фамилия',
        signIn: 'Регистрация',
        dataOfBirth: 'Дата рождения',
        workExperience: 'Опыт работы',
        currentWork: 'Текущая работа',
        grade: 'Класс',
        school: 'Школа',
        signUp: 'Зарегистрироваться',
        year: 'года',
    },
    KZ: {
        header: 'Тіркелу',
        teacher: 'Мектепке тұлғасы',
        student: 'Студент',
        email: 'Электрондық пошта',
        password: 'Пароль',
        firstName: 'Аты',
        lastName: 'Фамилия',
        signIn: 'Тіркелу',
        dataOfBirth: 'Туған күні',
        workExperience: 'Жұмыс қызметі',
        currentWork: 'Ағымдағы жұмыс',
        grade: 'Класс',
        school: 'Школа',
        signUp: 'Тіркелу',
        year: 'жыл',
    },
    EN: {
        header: 'Sign up',
        teacher: 'Teacher',
        student: 'Student',
        email: 'Email',
        password: 'Password',
        firstName: 'First name',
        lastName: 'Last name',
        signIn: 'Sign in',
        dataOfBirth: 'Date of birth',
        workExperience: 'Work experience',
        currentWork: 'Current work',
        grade: 'Grade',
        school: 'School',
        signUp: 'Sign up',
        year: 'year',
    },
}