export const studentsPageText = {
    RU: {
        header: 'Учителя',
        students: [
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            }, 
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
        ]
    },
    KZ: {
        header: 'Мұғалімдер',
        students: [
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            }, 
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
        ]
    },
    EN: {
        header: 'Teachers',
        students: [
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            }, 
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
            {
                firstName: 'Firstname',
                lastName: 'Secondname',
                studentEmail: 'student@email.com',
                password: 'password',
                dateOfBirth: '01-01-1991',
                grade: '8',
                placeOfStudy: 'NIS',
                avarageGrade: '4.7',
            },
        ]
    },
}